In [2]:
import torch

# 3x3 크기의 텐서 생성
x = torch.tensor([[1, 2, 3], 
                #   [4, 5, 6], 
                  [7, 8, 9]], dtype=torch.float)

# 각 행의 표준 편차 계산
# std_per = torch.mean(torch.std(x, dim=0))
std_per = torch.std(x, dim=0, keepdim=True)
std_per

tensor([[4.2426, 4.2426, 4.2426]])

In [5]:
t = torch.arange(3*5*7).view(3, 5, 7)
t

tensor([[[  0,   1,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12,  13],
         [ 14,  15,  16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25,  26,  27],
         [ 28,  29,  30,  31,  32,  33,  34]],

        [[ 35,  36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47,  48],
         [ 49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62],
         [ 63,  64,  65,  66,  67,  68,  69]],

        [[ 70,  71,  72,  73,  74,  75,  76],
         [ 77,  78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95,  96,  97],
         [ 98,  99, 100, 101, 102, 103, 104]]])

In [8]:
t2 = torch.tensor([4, 2, 3])
t2.size()

torch.Size([3])

In [14]:
t2.unsqueeze(1)

tensor([[4],
        [2],
        [3]])

In [13]:
t[t2.unsqueeze(1)]

IndexError: index 4 is out of bounds for dimension 0 with size 3

In [17]:
import torch

t = torch.arange(3*5*7).view(3, 5, 7)
rows = torch.tensor([4, 2, 3])

# 각 차원에 대한 인덱스 생성
batch_indices = torch.arange(t.size(0))  # 첫 번째 차원(배치 차원)을 위한 인덱스
# col_indices = torch.arange(t.size(2))  # 세 번째 차원(열 차원)을 위한 인덱스

# 결과 선택
selected = t[batch_indices, rows]  # batch_indices와 rows를 사용해 필요한 행을 선택, 모든 열을 포함

print(selected)

tensor([[28, 29, 30, 31, 32, 33, 34],
        [49, 50, 51, 52, 53, 54, 55],
        [91, 92, 93, 94, 95, 96, 97]])


In [2]:
import torch

# [3, 10, 32, 256] 크기의 텐서 생성
x = torch.randn(2, 3, 4, 5)

# [3, 10] 크기의 인덱스 텐서 생성, 예를 들어 여기서는 32보다 작은 임의의 정수를 선택
indices = torch.randint(0, 4, (2, 3))

# 인덱스 텐서의 크기를 조정하여 gather에 사용할 수 있도록 함
# 여기서는 세 번째 차원(인덱스 2)에서 요소를 선택하고자 하므로, 인덱스 텐서의 크기를 [3, 10, 1, 1]로 조정합니다.
indices = indices.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, -1, 5)

# torch.gather를 사용하여 원하는 요소 선택
# dim=2는 세 번째 차원에서 인덱싱을 수행하겠다는 것을 의미합니다.
result = torch.gather(x, 2, indices)

print(result.shape)  # 결과적으로 [3, 10, 1, 256] 크기의 텐서를 얻습니다.

print(x)
print(result)
torch.isnan(result).any()

torch.Size([2, 3, 1, 5])
tensor([[[[-2.2416, -0.9335, -0.1091, -0.8751,  1.7017],
          [-0.9493,  0.6737,  1.0425,  1.6600, -0.8463],
          [ 0.6690, -1.1850,  1.3416,  0.6131, -1.7261],
          [-1.2091,  0.4820,  1.4052,  1.5463,  1.2900]],

         [[ 0.0080,  0.6296,  1.1523, -1.7720, -0.8275],
          [-0.4476,  1.0355, -0.9121,  0.9403, -1.5383],
          [ 1.9812,  0.1521,  1.0496, -0.3971,  1.6726],
          [-0.7889, -0.2200,  0.6852,  0.9636,  1.6826]],

         [[-0.0222, -1.1725,  0.0880, -0.3017,  0.0338],
          [-0.2303, -0.4895, -1.9712, -1.0895,  1.4418],
          [ 0.5153,  0.0586, -1.6305,  0.3750, -0.6582],
          [-1.2648,  0.0697, -0.3617, -0.9210, -0.1959]]],


        [[[ 0.4013,  0.0548,  1.0281, -0.8447,  0.1573],
          [-0.1847,  0.9468, -0.0571,  1.1472,  2.3481],
          [-1.5240,  0.8287,  1.4842, -0.7634,  2.0313],
          [-0.8925,  0.1698, -0.5042,  0.1865, -0.8488]],

         [[-0.7752,  0.0194, -0.7373,  1.3206, -0.033

tensor(False)

In [ ]:
import torch

In [3]:
# [3, 10, 32, 256] 크기의 텐서 생성
x = torch.arange(2 * 3 * 4 * 5).view(2, 3, 4, 5)
x

tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])

In [4]:

# [3, 10] 크기의 인덱스 텐서 생성, 예를 들어 여기서는 32보다 작은 임의의 정수를 선택
indices = torch.randint(0, 3, (2, 3))
indices

tensor([[2, 0, 1],
        [2, 2, 2]])

In [5]:

# 인덱스 텐서의 크기를 조정하여 gather에 사용할 수 있도록 함
# 여기서는 세 번째 차원(인덱스 2)에서 요소를 선택하고자 하므로, 인덱스 텐서의 크기를 [3, 10, 1, 1]로 조정합니다.
indices = indices.unsqueeze(-1).unsqueeze(-1).expand(-1, -1, -1, 5)
indices

tensor([[[[2, 2, 2, 2, 2]],

         [[0, 0, 0, 0, 0]],

         [[1, 1, 1, 1, 1]]],


        [[[2, 2, 2, 2, 2]],

         [[2, 2, 2, 2, 2]],

         [[2, 2, 2, 2, 2]]]])

In [8]:

# torch.gather를 사용하여 원하는 요소 선택
# dim=2는 세 번째 차원에서 인덱싱을 수행하겠다는 것을 의미합니다.
result = torch.gather(x, 2, indices)
result


tensor([[[[ 10,  11,  12,  13,  14]],

         [[ 20,  21,  22,  23,  24]],

         [[ 45,  46,  47,  48,  49]]],


        [[[ 70,  71,  72,  73,  74]],

         [[ 90,  91,  92,  93,  94]],

         [[110, 111, 112, 113, 114]]]])

In [10]:

print(result.shape)  # 결과적으로 [3, 10, 1, 256] 크기의 텐서를 얻습니다.

torch.Size([2, 3, 1, 5])


In [11]:
torch.gather(x, 1, indices)

tensor([[[[ 40,  41,  42,  43,  44]],

         [[  0,   1,   2,   3,   4]],

         [[ 20,  21,  22,  23,  24]]],


        [[[100, 101, 102, 103, 104]],

         [[100, 101, 102, 103, 104]],

         [[100, 101, 102, 103, 104]]]])

In [12]:
x = torch.arange(2 * 3).view(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [19]:
indices = torch.randint(0, 2, (2, ))
indices = indices.unsqueeze(-1).expand(-1, 3)
indices

tensor([[1, 1, 1],
        [0, 0, 0]])

In [23]:
torch.gather(x, 1, indices)

tensor([[1, 1, 1],
        [3, 3, 3]])